server:
  port: 8402
spring:
  datasource:
    url: jdbc:postgresql://localhost:5440/ikea
    username: postgres
    password: 1234
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  spring:
    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 20MB